export const modulosConAcciones: Record<string, string[]> = {
    EMPRESAS: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    SUCURSALES: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    ALMACEN_SUCURSAL: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    AREAS: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    ALMACEN_AREA: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    MARCAS: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    CATEGORIAS: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    SUB_CATEGORIAS: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    PRODUCTOS: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    STOCK: ["LISTAR", "EDITAR", "ELIMINAR", "ASIGNAR STOCK"],

    PROVEEDOR_PERSONA: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    PROVEEDOR_EMPRESA: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    TRANSFERENCIAS: ["LISTAR", 
      "EDITAR", 
      "CANCELAR_TRANSFERENCIAS",
       "ELIMINAR", 
      "REALIZAR_TRANSFERENCIAS","RECIBIR_TRANSFERENCIAS","ACEPTAR", "RECHAZAR"],
      

    MOVIMIENTO_AREA: ["LISTAR"],

    MOVIMIENTO_SUCURSAL: ["LISTAR"],

    ROL: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    USUARIOS: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR", "TIPO_SUCURSAL",  "TIPO_AREA",  "TIPO_NIGUNO"],
    
    STOCK_SUCURSAL: ["LISTAR"],
  };