export const modulosConAcciones: Record<string, string[]> = {
    EMPRESAS: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    SUCURSALES: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    ALMACEN_SUCURSAL: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    AREAS: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    ALMACEN_AREA: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    MARCAS: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    CATEGORIAS: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    
    PRODUCTOS: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],

    STOCK: ["LISTAR", "EDITAR", "ELIMINAR", "ASIGNAR STOCK"],

    PROVEEDORES: ["LISTAR", "EDITAR", "ELIMINAR", "CREAR"],



    TRANSFERENCIAS: ["LISTAR", 
      "EDITAR", 
      "CANCELAR_TRANSFERENCIAS",
       "ELIMINAR", 
      "REALIZAR TRANSFERENCIAS","RECIBIR TRANSFERENCIAS","APROBAR", "RECHAZAR"],
      

    MOVIMIENTO_AREA: ["LISTAR"],

    MOVIMIENTO_SUCURSAL: ["LISTAR"],

    ROL: ["LISTAR ROL", "EDITAR", "ELIMINAR", "CREAR"],

    USUARIOS: ["LISTAR USUARIOS", "EDITAR", "ELIMINAR", "CREAR"],
    
    STOCK_SUCURSAL: ["LISTAR"],
  };